title: Kartr
description: Connect Influencers and Sponsors
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: jekyll-theme-primer
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - gemfiles
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/